apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: superset
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://apache.github.io/superset/
    targetRevision: 0.13.4
    chart: superset
    helm:
      releaseName: superset
      valuesObject:
        bootstrapScript: |
          #!/bin/bash
          pip install \
            "psycopg2-binary>=2.9.10" \
            &&\
          if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
        service:
          type: NodePort
          nodePort:
            http: 32648
        postgresql:
          enabled: true
          auth:
            database: superset  # The database name remains as 'superset'
        redis:
          enabled: true
          auth:
            enabled: false
        extraSecretEnv:
          SUPERSET_SECRET_KEY: <REDACTED>
        configOverrides:
          enable_feature: |
            FEATURE_FLAGS = {
             'ENABLE_TEMPLATE_PROCESSING': True
            }
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
